### ISSUE TITLE
Using project_name instead of project

### ISSUE THREAD

**Issue by jacques-comet** [comet-ml/comet-llm#40]
Hi,
Currently the `comet_llm` SDK uses the parameter `project` to indicate the Comet project name while the `comet_ml` SDK uses `project_name`.

Would it be possible to have consistency between the two SDK and have a `project_name` parameter in the `comet_llm` SDK ?

**Comment by dsblank** [comment]
Thank you for the suggestion. This has been changed. Let us know if you have any other suggestions :)
