### ISSUE TITLE
New evaluation feature suggestion

### ISSUE THREAD

**Issue by TheMrguiller** [comet-ml/comet-llm#97]
Hi,

I haven't used your tool yet, but I've come up with a significant improvement in the evaluation aspect of the prompts that have been created. Could it be possible to implement a machine-based approach for the evaluation of prompts instead of a manual human annotation process? Imagine iteratively generating prompts using new techniques available today, and you want to log the best one so far for a specific input or even a dataset. Obviously this machine annotation process will be user custom, no need to add yours in that aspect. Could it be possible to add this feature?

Thank you in advance.

**Comment by jverre** [comment]
Hey,

It is possible to log any metadata or tags with the prompt so that you can then filter and group your prompts in the Comet UI. Is this what you had in mind ?

**Comment by dsblank** [comment]
Closing due to staleness of response.
